name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        go: ["1.15.x", "1.16.x"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: start Jenkins
      run: bash ./start_jenkins.sh start
    - name: Test
      run: |
        # make lint
        # make build
        make test

